import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import NavBar from "../../components/NavBar";
import NextStep from "../../components/NextStep";
import Footer from "../../components/Footer";
import Chatbot from "../../components/Chatbot";
import "../globals.css";
import { ThemeProvider } from "../../components/theme-provider";
import { Toaster } from "../../components/ui/sonner";
import Script from "next/script";


const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Dzignex Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <Script
          defer
          src="https://cloud.umami.is/script.js"
          data-website-id="88862ea3-0787-4a41-b529-d603e616a87b"
          strategy="afterInteractive"
        />
      </head>
      <body className={[dmSans.className, "antialiased bg-dzignex-black text-white"].join(" ")}>
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
          <NavBar />
          {children}
          <NextStep />
          <Footer />
          <Toaster />
          <Chatbot />
        </ThemeProvider>
      </body>
    </html>
  );
}
