import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import NavBar from "../../components/NavBar";
import NextStep from "../../components/NextStep";
import Footer from "../../components/Footer";
import "../globals.css";


const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Dzignex Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${dmSans.className} antialiased bg-dzignex-black text-white`} >
        <NavBar />
        {children}
        <NextStep />
        <Footer />

      </body>
    </html>
  );
}
