import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import Navbar from "../components/NavBar";
import "./globals.css";
import Footer from "../components/sections/Footer";


const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Dzignex Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${dmSans.className} antialiased bg-[#000300]`} >
        <Navbar />
        {children}
        <Footer />

      </body>
    </html>
  );
}
