import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";


const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Dzignex Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${dmSans.className} antialiased bg-[#000300] `}
      >
<nav
  className="
    sticky top-0 z-50 w-full 
    bg-white/1 backdrop-blur-2xl 
    border-b border-white/5
    text-white
  "
>
  <div className="max-w-[1200px] mx-auto flex items-center justify-between px-4 py-3">
    <span className="font-bold text-xl">Dzignex Studio</span>
    <ul className="flex gap-6 list-none m-0 p-0">
      <li><a href="/" className="hover:text-blue-600">Home</a></li>
      <li><a href="/about" className="hover:text-blue-600">About</a></li>
      <li><a href="/contact" className="hover:text-blue-600">Projects</a></li>
      <li><a href="/contact" className="hover:text-blue-600">Testimonials</a></li>
      <li>
        <a
          href="/contact"
          className="bg-blue-500 px-3 py-2 rounded-lg text-white hover:bg-blue-600 transition"
        >
          Contact
        </a>
      </li>
    </ul>
  </div>
</nav>



        {children}
      </body>
    </html>
  );
}
