import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { AppSidebar } from "../../features/dashboard/components/app-sidebar"
import { SiteHeader } from "../../features/dashboard/components/site-header"
import {
  SidebarInset,
  SidebarProvider,
} from "../../features/dashboard/components/ui/sidebar"
import { auth } from "../../auth"
import { redirect } from "next/navigation"

import "../globals.css";


const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Dzignex Studio",
  description: "Generated by create next app",
};

import { ThemeProvider } from "../../components/theme-provider";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth()
  
  if (!session?.user) {
    redirect("/sign-in")
  }

  const user = {
    name: session.user.name ?? "",
    email: session.user.email ?? "",
    avatar: "", // Add avatar support later if available in user model
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` ${dmSans.className} antialiased`} >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider
            defaultOpen={false}
            style={
              {
                "--sidebar-width": "calc(var(--spacing) * 72)",
                "--header-height": "calc(var(--spacing) * 12)",
              } as React.CSSProperties
            }
          >
              <AppSidebar variant="inset" user={user} />
              <SidebarInset>
                <SiteHeader />
                {children}
              </SidebarInset>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
