import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import { AppSidebar } from "../../features/dashboard/components/app-sidebar"
import { ChartAreaInteractive } from "../../features/dashboard/components/chart-area-interactive"
import { DataTable } from "../../features/dashboard/components/data-table"
import { SectionCards } from "../../features/dashboard/components/section-cards"
import { SiteHeader } from "../../features/dashboard/components/site-header"
import {
  SidebarInset,
  SidebarProvider,
} from "../../features/dashboard/components/ui/sidebar"

import "../globals.css";


const dmSans = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Dzignex Studio",
  description: "Generated by create next app",
};

import { ThemeProvider } from "../../components/theme-provider";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={` ${dmSans.className} antialiased`} >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SidebarProvider
            style={
              {
                "--sidebar-width": "calc(var(--spacing) * 72)",
                "--header-height": "calc(var(--spacing) * 12)",
              } as React.CSSProperties
            }
          >
              <AppSidebar variant="inset" />
              <SidebarInset>
                <SiteHeader />
                {children}
              </SidebarInset>
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
